# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-06 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AeroMembersApp', '0003_auto_20170905_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AeroMembersApp.Company'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='companyuser',
            unique_together=set([('user', 'company')]),
        ),
    ]
