# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-16 15:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AeroMembersApp', '0003_auto_20171016_0613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userupvote',
            unique_together=set([('user', 'postId')]),
        ),
    ]
