# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-07 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMembersApp', '0004_auto_20170906_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='profile',
            new_name='user',
        ),
    ]
