# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-17 00:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMembersApp', '0004_auto_20171016_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
