# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-24 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMembersApp', '0005_auto_20171017_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='AeroMembersApp.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='editedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='quotedText',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
