# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-12 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMembersApp', '0006_auto_20171024_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naics',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='naics',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='activity_type',
            field=models.CharField(choices=[('CM', 'Contract Management'), ('DES', 'Design'), ('ENG', 'Engineering'), ('FM', 'Facility Management'), ('GM', 'General Management'), ('HR', 'Human Resources'), ('IT', 'IT'), ('ME', 'Manufacturing Engineering'), ('MKT', 'Marketing'), ('OP', 'Operations'), ('PLN', 'Planning'), ('PROD', 'Production'), ('PRCH', 'Purchasing'), ('QA', 'Quality'), ('RD', 'R&D'), ('RW', 'Repair & Warranty'), ('SAL', 'Sales'), ('SCM', 'Supply Chain Management')], max_length=200),
        ),
        migrations.DeleteModel(
            name='NAICS',
        ),
    ]
