# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-13 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AeroMembersApp', '0007_auto_20180112_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
